name: Code Quality Checks

on: [push, pull_request]

jobs:
  biome:
    name: Biome (Lint, Format, Organize Imports)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Biome checks
        run: npx @biomejs/biome ci
  
  pre-commit-validation:
    name: Validate Pre-commit Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Python for pre-commit
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install pre-commit
        run: pipx install pre-commit
      
      - name: Run pre-commit on all files
        run: pre-commit run --all-files
